import { ref } from "vue";

export interface PageMapEntry {
  /** 1-based page number in the original PDF */
  page: number;
  /** Character offset in the markdown content where this page starts */
  startChar: number;
}

/**
 * Composable for multi-directional navigation between Markdown, PDF, and Chunks.
 *
 * Data sources:
 * - page_map.cache: Generated by MinerU after parsing, maps PDF page → markdown startChar
 * - chunk metadata: LanceDB stores page_number, start_char for each chunk
 * - page anchors: <!-- page-N --> comments injected into markdown
 */
export function usePageNavigation() {
  const currentView = ref<"markdown" | "pdf" | "split">("markdown");
  const scrollTarget = ref<{ type: "page" | "chunk" | "section"; id: string } | null>(null);

  /** Parse page_map.cache content into structured entries */
  function parsePageMap(cacheContent: string): PageMapEntry[] {
    try {
      const parsed = JSON.parse(cacheContent);
      // Support both array and object formats
      if (Array.isArray(parsed)) {
        return parsed.map((e: any) => ({
          page: e.page ?? e.page_number ?? 0,
          startChar: e.start_char ?? e.startChar ?? 0,
        })).filter((e) => e.page > 0).sort((a, b) => a.page - b.page);
      }
      if (typeof parsed === "object") {
        return Object.entries(parsed).map(([key, val]: [string, any]) => ({
          page: parseInt(key) || (val.page ?? 0),
          startChar: val.start_char ?? val.startChar ?? 0,
        })).filter((e) => e.page > 0).sort((a, b) => a.page - b.page);
      }
      return [];
    } catch {
      // If not valid JSON, try line-by-line format
      return cacheContent.split("\n")
        .filter((line) => line.trim())
        .map((line) => {
          const parts = line.split(/[\t,=:]/);
          return { page: parseInt(parts[0]) || 0, startChar: parseInt(parts[1]) || 0 };
        })
        .filter((e) => e.page > 0);
    }
  }

  /** Build a map: page number → startChar for O(1) lookup */
  function buildPageMap(entries: PageMapEntry[]): Map<number, number> {
    const map = new Map<number, number>();
    for (const e of entries) map.set(e.page, e.startChar);
    return map;
  }

  /** Given a PDF page number, find the corresponding markdown section anchor */
  function getMarkdownAnchorFromPage(page: number, pageMap: Map<number, number>): string | null {
    const char = pageMap.get(page);
    if (char == null) return null;
    // Map char back to the page anchor that contains it
    return `page-${page}`;
  }

  /** Given a chunk with page_number, find the markdown anchor */
  function getMarkdownAnchorFromChunk(chunk: { page_number?: number; start_char?: number }): string | null {
    if (chunk.page_number) return `page-${chunk.page_number}`;
    return null;
  }

  /** Build source badge ↔ chunk mapping for bidirectional linking */
  function getChunkFromBadge(badgeIndex: number, chunks: any[]): any | null {
    return chunks[badgeIndex] ?? null;
  }

  /** Find chunks that belong to a given PDF page */
  function getChunksByPage(page: number, allChunks: any[]): any[] {
    return allChunks.filter((c) => c.page_number === page || c.metadata?.page === page);
  }

  /** Navigate to a target */
  function navigate(type: "page" | "chunk" | "section", id: string) {
    scrollTarget.value = { type, id };
  }

  /** Clear scroll target after it's been handled */
  function didNavigate() {
    scrollTarget.value = null;
  }

  return {
    currentView,
    scrollTarget,
    parsePageMap,
    buildPageMap,
    getMarkdownAnchorFromPage,
    getMarkdownAnchorFromChunk,
    getChunkFromBadge,
    getChunksByPage,
    navigate,
    didNavigate,
  };
}
